export const BREEDS = [
  'Beagle',
  'Border Collie',
  'Boxer',
  'Bulldog',
  'Chihuahua',
  'Cocker Spaniel',
  'Dachshund',
  'Dalmatian',
  'Doberman',
  'French Bulldog',
  'German Shepherd',
  'Golden Retriever',
  'Great Dane',
  'Husky',
  'Jack Russell Terrier',
  'Labrador Retriever',
  'Maltese',
  'Pomeranian',
  'Poodle',
  'Rottweiler',
  'Shih Tzu',
  'Yorkshire Terrier',
] as const;
